assert = require("luassert")

describe("pluralize", function()
  local Inflector = require("go-to-factory-bot.inflector")

  local function subject(word)
    return Inflector.pluralize(word)
  end

  describe("basic words", function()
    it("adds 's'", function() assert.equals(subject("book"), "books") end)
    it("adds 's'", function() assert.equals(subject("car"), "cars") end)
    it("adds 's'", function() assert.equals(subject("computer"), "computers") end)
    it("adds 's'", function() assert.equals(subject("dog"), "dogs") end)
    it("adds 's'", function() assert.equals(subject("hotel"), "hotels") end)
    it("adds 's'", function() assert.equals(subject("key"), "keys") end)
    it("adds 's'", function() assert.equals(subject("mistake"), "mistakes") end)
    it("adds 's'", function() assert.equals(subject("shop"), "shops") end)
    it("adds 's'", function() assert.equals(subject("tongue"), "tongues") end)

    -- 母音 + "y"
    it("adds 's'", function() assert.equals(subject("boy"), "boys") end)
    it("adds 's'", function() assert.equals(subject("day"), "days") end)
    it("adds 's'", function() assert.equals(subject("valley"), "valleys") end)
    it("adds 's'", function() assert.equals(subject("guy"), "guys") end)

    -- 母音 + "o"
    it("adds 's'", function() assert.equals(subject("bamboo"), "bamboos") end)
    it("adds 's'", function() assert.equals(subject("kangaroo"), "kangaroos") end)
    it("adds 's'", function() assert.equals(subject("zoo"), "zoos") end)
  end)

  describe("words ending with 's'", function()
    it("adds 'es'", function() assert.equals(subject("address"), "addresses") end)
    it("adds 'es'", function() assert.equals(subject("boss"), "bosses") end)
    it("adds 'es'", function() assert.equals(subject("bus"), "buses") end)
    it("adds 'es'", function() assert.equals(subject("class"), "classes") end)
    it("adds 'es'", function() assert.equals(subject("lens"), "lenses") end)
    it("adds 'es'", function() assert.equals(subject("miss"), "misses") end)
    it("adds 'es'", function() assert.equals(subject("toss"), "tosses") end)
  end)

  describe("words ending with 'x'", function()
    it("adds 'es'", function() assert.equals(subject("ax"), "axes") end)
    it("adds 'es'", function() assert.equals(subject("box"), "boxes") end)
    it("adds 'es'", function() assert.equals(subject("fox"), "foxes") end)
  end)

  describe("words ending with 'sh'", function()
    it("adds 'es'", function() assert.equals(subject("brush"), "brushes") end)
    it("adds 'es'", function() assert.equals(subject("bush"), "bushes") end)
    it("adds 'es'", function() assert.equals(subject("dish"), "dishes") end)
    it("adds 'es'", function() assert.equals(subject("flash"), "flashes") end)
    it("adds 'es'", function() assert.equals(subject("radish"), "radishes") end)
    it("adds 'es'", function() assert.equals(subject("rush"), "rushes") end)
    it("adds 'es'", function() assert.equals(subject("wish"), "wishes") end)
  end)

  describe("words ending with 'ch'", function()
    it("adds 'es'", function() assert.equals(subject("bench"), "benches") end)
    it("adds 'es'", function() assert.equals(subject("branch"), "branches") end)
    it("adds 'es'", function() assert.equals(subject("church"), "churches") end)
    it("adds 'es'", function() assert.equals(subject("coach"), "coaches") end)
    it("adds 'es'", function() assert.equals(subject("match"), "matches") end)
    it("adds 'es'", function() assert.equals(subject("peach"), "peaches") end)
    it("adds 'es'", function() assert.equals(subject("sandwich"), "sandwiches") end)
    it("adds 'es'", function() assert.equals(subject("watch"), "watches") end)
    -- it("adds 'es'", function() assert.equals(subject("stomach"), "stomachs") end)
  end)

  -- consonant: 子音
  describe("words ending with consonant + 'o'", function()
    it("adds 'es'", function() assert.equals(subject("buffalo"), "buffaloes") end)
    it("adds 'es'", function() assert.equals(subject("cargo"), "cargoes") end)
    it("adds 'es'", function() assert.equals(subject("hero"), "heroes") end)
    it("adds 'es'", function() assert.equals(subject("mosquito"), "mosquitoes") end)
    it("adds 'es'", function() assert.equals(subject("motto"), "mottoes") end)
    it("adds 'es'", function() assert.equals(subject("potato"), "potatoes") end)
    it("adds 'es'", function() assert.equals(subject("tomato"), "tomatoes") end)

    -- TODO: 子音 + "o" だが s をつけるだけ
    -- it("adds 'es'", function() assert.equals(inflector.pluralize("solo"), "solos") end)
    -- it("adds 'es'", function() assert.equals(inflector.pluralize("tobacco"), "tobaccos") end)
    -- it("adds 'es'", function() assert.equals(inflector.pluralize("piano"), "pianos") end)
    -- it("adds 'es'", function() assert.equals(inflector.pluralize("photo"), "photos") end)
  end)

  describe("words ending with consonant + 'y'", function()
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("baby"), "babies") end)
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("city"), "cities") end)
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("country"), "countries") end)
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("dictionary"), "dictionaries") end)
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("family"), "families") end)
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("fly"), "flies") end)
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("lady"), "ladies") end)
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("secretary"), "secretaries") end)
    it("converts 'y' to 'i' and adds 'es'", function() assert.equals(subject("story"), "stories") end)
  end)

  describe("words ending with 'f'", function()
    it("converts 'f' to 'v' and adds 'es'", function() assert.equals(subject("leaf"), "leaves") end)
    it("converts 'f' to 'v' and adds 'es'", function() assert.equals(subject("shelf"), "shelves") end)
    it("converts 'f' to 'v' and adds 'es'", function() assert.equals(subject("wolf"), "wolves") end)

    -- TODO: 語尾が "f" or "fe" だが s をつけるだけ
    -- it("converts 'f' to 'v' and adds 'es'", function() assert.equals(inflector.pluralize("belief"), "beliefs") end)
    -- it("converts 'f' to 'v' and adds 'es'", function() assert.equals(inflector.pluralize("chief"), "chiefs") end)
    -- it("converts 'f' to 'v' and adds 'es'", function() assert.equals(inflector.pluralize("roof"), "roofs") end)
  end)

  describe("words ending with 'fe'", function()
    it("converts 'fe' to 'v' and adds 'es'", function() assert.equals(subject("knife"), "knives") end)
    it("converts 'fe' to 'v' and adds 'es'", function() assert.equals(subject("life"), "lives") end)
    it("converts 'fe' to 'v' and adds 'es'", function() assert.equals(subject("thief"), "thieves") end)
    it("converts 'fe' to 'v' and adds 'es'", function() assert.equals(subject("wife"), "wives") end)
  end)

  describe("irregular words", function()
    it("converts according to patterns", function() assert.equals(subject("analysis"), "analyses") end)
    it("converts according to patterns", function() assert.equals(subject("axis"), "axes") end)
    it("converts according to patterns", function() assert.equals(subject("basis"), "bases") end)
    it("converts according to patterns", function() assert.equals(subject("child"), "children") end)
    it("converts according to patterns", function() assert.equals(subject("crisis"), "crises") end)
    it("converts according to patterns", function() assert.equals(subject("datum"), "data") end)
    it("converts according to patterns", function() assert.equals(subject("foot"), "feet") end)
    it("converts according to patterns", function() assert.equals(subject("formula"), "formulae") end)
    it("converts according to patterns", function() assert.equals(subject("goose"), "geese") end)
    it("converts according to patterns", function() assert.equals(subject("hypothesis"), "hypotheses") end)
    it("converts according to patterns", function() assert.equals(subject("index"), "indices") end)
    it("converts according to patterns", function() assert.equals(subject("larva"), "larvae") end)
    it("converts according to patterns", function() assert.equals(subject("man"), "men") end)
    it("converts according to patterns", function() assert.equals(subject("medium"), "media") end)
    it("converts according to patterns", function() assert.equals(subject("memorandum"), "memoranda") end)
    it("converts according to patterns", function() assert.equals(subject("mouse"), "mice") end)
    it("converts according to patterns", function() assert.equals(subject("octopus"), "octopi") end)
    it("converts according to patterns", function() assert.equals(subject("ox"), "oxen") end)
    it("converts according to patterns", function() assert.equals(subject("passerby"), "passersby") end)
    it("converts according to patterns", function() assert.equals(subject("phenomenon"), "phenomena") end)
    it("converts according to patterns", function() assert.equals(subject("quiz"), "quizzes") end)
    it("converts according to patterns", function() assert.equals(subject("stimulus"), "stimuli") end)
    it("converts according to patterns", function() assert.equals(subject("tooth"), "teeth") end)
    it("converts according to patterns", function() assert.equals(subject("woman"), "women") end)
  end)

  describe("empty word", function()
    it("returns empty string", function() assert.equals(subject(""), "") end)
  end)

  describe("word of length 1", function()
    it("returns word as it is", function() assert.equals(subject("a"), "a") end)
  end)
end)
